---
version: '3.5'
services:
  ruwebfiles:
    build:
      context: "./ruWebfiles"
      args:
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
    volumes:
      - "./public_html/:/app/"
      - "./torrents/:/torrents/"
      - "./security/:/security/"
    depends_on:
      - php
    environment:
      - RUREPO=${RUREPO}
      - APP_USER=${APP_USER}
      - APP_GROUP=${APP_GROUP}
    restart: 'no'
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_SERVER}"
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: rutorrent,build
  caddy:
    build:
      context: "./caddy"
      args:
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
    restart: unless-stopped
    tmpfs:
      - "/tmp"
    volumes:
      - "./public_html/:${PHP_APP_DIR}/"
      - "./logs/caddy/:/log/"
      - "./security/caddy/:/etc/caddyusers/"
      - "./certs/data:/data"
      - "./certs/config:/config"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - ruwebfiles
    environment:
      - CADDYPATH=/etc/caddycerts
      - APP_USER=${APP_USER}
      - APP_GROUP=${APP_GROUP}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - TLS_EMAIL=${TLS_EMAIL}
      - ACME_AGREE=true
    networks:
      - frontend
      - backend
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_SERVER}"
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: caddy
  php:
    build:
      context: "./php"
      args:
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    working_dir: "${PHP_APP_DIR}"
    tmpfs:
      - "/tmp"
    volumes:
      - "./public_html/:${PHP_APP_DIR}/"
      - "./logs/php/:${PHP_ROOT_DIR}/logs/"
      - "./torrents/:/torrents/"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend
      - torrent
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APP_USER=${APP_USER}
      - APP_GROUP=${APP_GROUP}
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_SERVER}"
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: rutorrent,php
  rutorrent_media:
    build:
      context: "./ruTorrent"
      args:
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
        - RUUSER=${MEDIA_USERNAME}
        - PORT=${MEDIA_PORT}
        - DHTPORT=${MEDIA_DHT}
    depends_on:
      - ruwebfiles
    environment:
      - FILEBOT_LICENSE_BASE64=${FILEBOT_LICENSE_BASE64}
      - APP_USER=${APP_USER}
      - APP_GROUP=${APP_GROUP}
      - RUUSER=${MEDIA_USERNAME}
      - PASSWORD=${MEDIA_PASSWORD}
      - PORT=${MEDIA_PORT}
      - DHTPORT=${MEDIA_DHT}
      - OSDB_USER=${OSDB_USERNAME}
      - OSDB_PASSWORD=${OSDB_PASSWORD}
    networks:
      - torrent
    tmpfs:
      - "/tmp"
    volumes:
      - "./torrents/:/torrents/"
      - "./public_html/:/app/"
      - "./security/:/app-data/"
      - "./filebot/:/torrents/${MEDIA_USERNAME}/.filebot/"
      - "parta:/torrents/${MEDIA_USERNAME}/media/TV:rw"
      - "partb:/torrents/${MEDIA_USERNAME}/media/Movie:rw"
    ports:
      - 6881:6881
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_SERVER}"
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: rutorrent,torrent-media
  rutorrent_other:
    build:
      context: "./ruTorrent"
      args:
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
        - RUUSER=${OTHER_USERNAME}
        - PORT=${OTHER_PORT}
        - DHTPORT=${OTHER_DHT}
    depends_on:
      - ruwebfiles
    environment:
      - FILEBOT_LICENSE_BASE64=${FILEBOT_LICENSE_BASE64}
      - APP_USER=${APP_USER}
      - APP_GROUP=${APP_GROUP}
      - RUUSER=${OTHER_USERNAME}
      - PASSWORD=${OTHER_PASSWORD}
      - PORT=${OTHER_PORT}
      - DHTPORT=${OTHER_DHT}
      - OSDB_USER=${OSDB_USERNAME}
      - OSDB_PASSWORD=${OSDB_PASSWORD}
    networks:
      - torrent
    tmpfs:
      - "/tmp"
    volumes:
      - "./torrents/:/torrents/"
      - "./public_html/:/app/"
      - "./security/:/app-data/"
      - "./filebot/:/torrents/${OTHER_USERNAME}/.filebot/"
      - "partc:/torrents/${OTHER_USERNAME}/upload:rw"
    ports:
      - 6882:6882
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "${GELF_SERVER}"
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: rutorrent,torrent-other
networks:
  frontend:
  backend:
  torrent:
volumes:
  parta:
    driver: rclone:latest
    driver_opts:
      remote: 'parta-crypt:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
  partb:
    driver: rclone:latest
    driver_opts:
      remote: 'partb-crypt:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
  partc:
    driver: rclone:latest
    driver_opts:
      remote: 'partc-crypt:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
  olda:
    driver: rclone:latest
    driver_opts:
      remote: 'olda:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
